name: pytorchbook
channels:
  - pytorch
  - nvidia
  - conda-forge
  - dglteam
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - pip:
    - torchviz
    - tensorboard
    - jupyter-server-proxy